apiVersion: v1
kind: Service
metadata:
  name: kube-credential-system-frontend
spec:
  type: NodePort
  selector:
    app: kube-credential-system-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
