apiVersion: v1
kind: Service
metadata:
  name: kube-credential-system-backend-verification
spec:
  type: NodePort
  selector:
    app: kube-credential-system-backend-verification
  ports:
    - port: 9002
      targetPort: 3002
      nodePort: 30082
