apiVersion: v1
kind: Service
metadata:
  name: kube-credential-system-backend-issuance
spec:
  type: NodePort
  selector:
    app: kube-credential-system-backend-issuance
  ports:
    - port: 9001
      targetPort: 3001
      nodePort: 30081
